// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy3gskkYmQeb6n1weLRUhFPpft7BdzN5g',
    appId: '1:188586367856:web:0edc34643c8e715b9ecdb5',
    messagingSenderId: '188586367856',
    projectId: 'volsignalement',
    authDomain: 'volsignalement.firebaseapp.com',
    storageBucket: 'volsignalement.firebasestorage.app',
    measurementId: 'G-RT4HMWT7YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUJynvUV7q0dfK3dmDCWwjthz9jCGtspc',
    appId: '1:188586367856:android:73f9846234bfea029ecdb5',
    messagingSenderId: '188586367856',
    projectId: 'volsignalement',
    storageBucket: 'volsignalement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV8hAYW9aP9Bq-lLtK81ofvcDO4fh3nsU',
    appId: '1:188586367856:ios:6f851384124005269ecdb5',
    messagingSenderId: '188586367856',
    projectId: 'volsignalement',
    storageBucket: 'volsignalement.firebasestorage.app',
    iosBundleId: 'com.example.volSignalement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy3gskkYmQeb6n1weLRUhFPpft7BdzN5g',
    appId: '1:188586367856:web:fa9494ed323b83839ecdb5',
    messagingSenderId: '188586367856',
    projectId: 'volsignalement',
    authDomain: 'volsignalement.firebaseapp.com',
    storageBucket: 'volsignalement.firebasestorage.app',
    measurementId: 'G-4RZ6L965S5',
  );
}
